DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS heartbeats;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL
);

CREATE TABLE heartbeats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    heartbeat INTEGER,
    user_id INTEGER,
    FOREIGN KEY(user_id) REFERENCES users(id)
);

